##  Fei原创
##  原地址:https://github.com/Infatuation-Fei/rule/blob/main/Clash/GeneralConfig.yml


mixed-port: 7998
allow-lan: true
bind-address: '*'
authentication:
  - admim:123123
#SOCKS5/HTTP(S)代理验证(相当于设置了密码)，可选，但最好加上。--jan
mode: rule
log-level: info
ipv6: false


;; external-controller: 127.0.0.1:9090   #外部控制器,可以使用 RESTful API 来控制你的 clash 内核
;; secret:67559496  #API授权验证(相当于设置了密码)，可选，但最好加上这个--jan
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'lens.l.google.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
## 下面几条为实验，其中“network-test.debian.org” 为冲浪板“always-real-ip”真实存在   
    - 'network-test.debian.org'
    - 'www.baidu.com'
    - 'www.google.com.hk'
  nameserver:
    - https://dns.alidns.com/dns-query
##    - https://doh.pub/dns-query

##script:
##  shortcuts:
##    quic: network == 'udp' and (dst_port == 443 or dst_port == 4483 or dst_port == 9305)
##    BilibiliUdp: network == "udp" and match_provider("BiliBili")
    
##rules:
##  - DOMAIN,r2s.asuka.ga,DIRECT
##  - SCRIPT,quic,REJECT
##  - SCRIPT,BilibiliUdp,REJECT
